image: docker:latest

services:
  - docker:dind

before_script:
  - apk add git
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build_excel_erpnext_nginx:
  stage: build
  only:
    - tags
  script:
    - export VERSION=$(git tag --list --sort=-version:refname | sed -n 1p | sed -e 's#.*@\(\)#\1#')
    - docker build -t excel-erpnext-nginx docker/excel-erpnext-nginx
    - docker tag excel-erpnext-nginx "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:$VERSION"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:$VERSION"

build_excel_erpnext_worker:
  stage: build
  only:
    - tags
  script:
    - export VERSION=$(git tag --list --sort=-version:refname | sed -n 1p | sed -e 's#.*@\(\)#\1#')
    - docker build -t excel-erpnext-worker docker/excel-erpnext-worker
    - docker tag excel-erpnext-worker "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:$VERSION"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:$VERSION"

build_staging_excel_erpnext_nginx:
  stage: build
  only:
    refs:
      - version-12
  script:
    - docker build -t excel-erpnext-nginx docker/excel-erpnext-nginx
    - docker tag excel-erpnext-nginx "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:latest"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-nginx:latest"

build_staging_excel_erpnext_worker:
  stage: build
  only:
    refs:
      - version-12
  script:
    - docker build -t excel-erpnext-worker docker/excel-erpnext-worker
    - docker tag excel-erpnext-worker "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:latest"
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/excel_erpnext/excel-erpnext-worker:latest"
